SVCPLAN-785 - create profile_lvm
ncsa/puppet-profile_lvm pull request #1
Opened 2022-04-27 00:21 UTC by jakerundall

define profile_lvm, using lvm module

include support for bindmounts from (subdirectories within) LVs

2022-04-27 14:01 UTC, billglick requested changes
A few minor suggestions and questions...

2022-04-27 14:01 UTC, billglick commented on manifests/bindmounts.pp
> +  $map.each | $k, $v | {
In the `lvm` module port, we wrapped essentially this same logic with an `if $map`. Do we need that same logic here?

2022-04-27 14:01 UTC, billglick commented on manifests/init.pp
> +  Optional[Array]                 $required_pkgs,
Why are these optional?

We actually provide all of them via the module's default data.

2022-04-27 14:01 UTC, billglick commented on README.md
Link in the ncsa/lvm ported module

2022-04-27 14:01 UTC, billglick commented on README.md
> +LVs).
Can you add example hiera for this? Ideally related to the `lvs` example above.

2022-04-29 18:54 UTC, jakerundall commented on manifests/bindmounts.pp
> +  $map.each | $k, $v | {
Yes! Updating.

2022-04-29 18:58 UTC, jakerundall commented on manifests/init.pp
> +  Optional[Array]                 $required_pkgs,
Fixed.

2022-04-30 18:54 UTC, jakerundall commented on README.md
Done.

2022-04-30 18:55 UTC, jakerundall commented on README.md
> +LVs).
Added that example (for slurm, and switched the original lv to slurm as well) and examples for a couple of the other params.

2022-04-30 18:58 UTC, jakerundall commented
@billglick Should be all fixed and ready for you to take another look. Thanks!

2022-04-30 18:59 UTC, jakerundall commented
NOTE: Somehow the main branch got created as master, so after I merge I will be renaming that to main.

2022-05-02 16:46 UTC, billglick approved these changes
Looks good.

2022-05-02 19:15 UTC, merged